# Generated by Django 4.2.11 on 2024-06-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0005_seat_start_time_seat_usage_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='usage_time',
            new_name='expected_duration',
        ),
    ]
