# Generated by Django 4.2.11 on 2024-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0006_rename_usage_time_seat_expected_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='expected_duration',
        ),
        migrations.AddField(
            model_name='seat',
            name='estimated_using_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
