# Generated by Django 4.2.11 on 2024-06-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0007_remove_seat_expected_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='estimated_using_time',
        ),
        migrations.AddField(
            model_name='seat',
            name='expected_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
