# Generated by Django 4.2.11 on 2024-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0008_remove_seat_estimated_using_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='expected_duration',
        ),
        migrations.AddField(
            model_name='seat',
            name='estimated_using_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
