# Generated by Django 4.2.11 on 2024-06-03 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usage', '0009_remove_seat_expected_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='estimated_using_time',
        ),
        migrations.AddField(
            model_name='seat',
            name='expected_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
