# Generated by Django 4.2.11 on 2024-06-03 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usage', '0011_seat_usage_type_alter_seat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='usage_type',
        ),
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
